"go.lintTool": "golangci-lint"
"go.lintFlags": [
  "--fast"
]
linters:
  enable:
    - golint
    - errcheck
    - staticcheck
    - unused
    - typecheck

linters-settings:
  golint:
    enable: true