version: "3.8"

services:
  postgres:
    restart: "always"
    container_name: "book-services"
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: books
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - ./pg:/var/lib/postgresql/data/pgdata
    